### PR TITLE
Include raw as an option

### PR DESCRIPTION
**Pull request by sieben**
Raw packet hex data can only be printed as text, PostScript, JSON or EK JSON

### CODE REVIEW

**Comment by sieben** [comment]
ping

**Comment by KimiNewt** [comment]
I don't think that if someone picks raw=True it should immediately enable JSON mode. That is not the behaviour a user might expect. Both would have to be true.

**Comment by sieben** [comment]
@KimiNewt fixed

**Comment by KimiNewt** [comment]
Sorry to bug about this, but I really think there should be some sort of exception if it's enabled and json_mode isn't. Otherwise, a user might do raw=True and it won't work and he won't know why (if he hasn't read the docks). An assertion or exception should be good

**Pull request closed without merging**
