### PR TITLE
Layer to take into account nested fields

### PR DESCRIPTION
**Pull request by JuhPuur**
## Description
There are two issues with nested fields not being parsed correctly by the Layer class init.
* https://github.com/KimiNewt/pyshark/issues/102
* https://github.com/KimiNewt/pyshark/issues/160

The issues both describe the same problem stemming from the use of ".//field" rather than "./field", which flattens the tree structure, thus discarding data.

## Solution
* Switched to recursively parsing fields with "./field".
* Added field and proto attributes to LayerField and a recursing function.

The proto I put in because I've encountered a few instances where a field has contained a proto.
I aimed to make this backwards compatible so that a flat structure is still parsed correctly as a flat structure.

### Other
Closed earlier pull request https://github.com/KimiNewt/pyshark/pull/165 so that I could putter around in the master branch.
There are obvious needs for changes in other functions to take nested fields into account.

### CODE REVIEW

**Comment by JuhPuur** [comment]
CI is unstable. Python2.7 succeeded on second try. First try failed on OSError(tshark had already closed).

**Comment by KimiNewt** [comment]
I'm a tad worried about performance. We're already slow as it is and the slowest thing is the initialization of layers.

If you can do a comparison that'll be nice, otherwise i'll try to do it myself later.

**Comment by JuhPuur** [comment]
Ran a series of tests on a 331kB/4383 packet pcap file using cProfile to measure performance. Most of the packets in the file have nested fields.
Test loads file, iterates through the packets and exits. Ran 4 iterations for both branches.

A "tad" looks to be insufficient. This branch takes 3 times as long in the test.
I'm using cProfile to look at what takes the most time, and with recursive field parsing most of the time is spend building path lxml iterators.

**Comment by JuhPuur** [comment]
I got it down to 12s vs 9s in master by getting rid of xpath processing. Will have a longer look at this option.

**Comment by JuhPuur** [comment]
Now down to 7.5s vs 9s. I think we can call that an improvement. The largest time consumers are now the file read followed closely by Layer.objectify() and lxml.objectify.fromstring().

As far as I can tell the output is identical. Can you verify?

**Comment by Tristou27** [comment]
Hi,
Re-opening this PR..

any news regarding this  ? why is it not merged within KimiNewt:master ? 
or is there another way to deal with nested fields ? 

Thanks

**Comment by JuhPuur** [comment]
I've had this tab open for two years. Horrible. I was just about to close it.
@Tristou27 I haven't checked what the current status is, but at least at the time pyshark flattened the tree structure of nested fields and made it useless. This PR sat for a year without action so I abandoned it.

**Pull request closed without merging**
