### PR TITLE
Using OrderedDict to keep json fields' order

### PR DESCRIPTION
**Pull request by janospapp**

### CODE REVIEW

**Comment by KimiNewt** [comment]
I'm afraid of this having any influence over performance. Why is it important to have the json fields ordered?

**Comment by janospapp** [comment]
I'd like to process MEGACO messages. For some reason tshark produces the following json output for some parts of MEGACO messages:
"b=AS:134": "",
"a=rtpmap:9 G722\/8000": "",
"a=rtpmap:8 PCMA\/8000": "",
"a=rtpmap:110 telephone-event\/8000": "",
"a=ptime:40": "",
"a=maxptime:40": "",

As you can see, the message lines will be the keys, all with empty string values. But I need the original order of the message lines in order to reconstruct it. That's why I need to use OrderedDict.

If it causes performance issues, then It's ok to reject my PR, I can use my private fork for my purpose. I just thought it could be useful for others as well.

**Comment by audeoudh** [comment]
IMO this is no more required when using Python 3.7, from where standard `dict` keeps insertion order.  What is the pyshark's minimum supported version of Python?  (FYI, Debian current stable version has Python 3.9; Debian current oldstable has 3.7; Debian current oldoldstable (still supported) has Python 3.5).

**Comment by XChikuX** [comment]
This is a stale issue. Please close!
Starting python3.6 dictionaries are automatically ordered. Since it was proven to provide higher performance.
https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6

**Pull request closed without merging**
