### PR TITLE
Added capture filter.

### PR DESCRIPTION
**Pull request by yozik04**
Capture filter is usually better for a live capture than display filter.

### CODE REVIEW

**Comment by KimiNewt** [comment]
Hi @yozik04 , if I recall correctly, this is a feature that existed but was removed because of some issues. I can't for the life of me remember exactly what they were, I'll have to try testing it a bit more. If you could do the same that'll speed it up. If we see no issues I'll merge it.

**Comment by yozik04** [comment]
I am currently using it on my Raspberry Pi. Works perfectly. Runs as a daemon and sniffs wifi traffic =). Want to do some presence detection. Feature can have some issues with older/newer tshark. My tshark version is 1.12.1

I think it is safe to merge as it is an extra feature that is not enabled by default.

**Comment by ttimasdf** [comment]
As to the `LiveCapture`, what is the difference between capture filter and display filter?

**Comment by yozik04** [comment]
Display filter is good when you have a capture file already and you need to see some packets in it. Capture filter is good to do live capture for only packets that match the filter. Display filter will also work for live captures but it will be more CPU intensive because it will capture all packets and them filter them out. This is my thinking.

```
$ tshark --help 2>&1 | grep filter
  -f <capture filter>      packet filter in libpcap filter syntax
  -R <read filter>         packet Read filter in Wireshark display filter syntax
  -Y <display filter>      packet displaY filter in Wireshark display filter
```

**Comment by ttimasdf** [comment]
Oh, that's great. I've noticed more CPU usage applying display_filter than bpf_filter. Maybe this option should be better.

By the way, there is no option of capture filters in the wireshark GUI. Did I miss anything？

**Comment by KimiNewt** [comment]
@ttimasdf It's in the capture options (when you select an interface). On the whole, capture (BPF) filters are always better if there is a simple one you can use (they're limited in scope, however, and will fail if you have some weird encapsulation or something).

**Pull request merged**
