### PR TITLE
Migrate to a more standard project layout

### PR DESCRIPTION
**Pull request by sieben**
https://python-guide.readthedocs.io/en/latest/writing/structure/

### CODE REVIEW

**Comment by sieben** [comment]
ping

**Comment by sieben** [comment]
@KimiNewt ping again :-) I've rebased on top of master.

**Comment by KimiNewt** [comment]
TBH I'm not sure about this structure, and I personally know projects that rely on the structure (though they obviously shouldn't). At any rate, I'd prefer not to do that right now, maybe after I finish the docs. I'll merge your other PR if it's over the old structure

**Comment by SerhiyRomanov** [comment]
I have a problem when i fork this and try to install this via pip from my repo. 
`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-21rn1l9x-build/setup.py'`

Maybe this related to this and really should to change project structure!

**Pull request closed without merging**
